-- Demo ejecutivo (app Capture): tester@ainspecciona.com / test@ainspecciona.com · clave Test1234A
--
-- Preferí ejecutar desde repo (actualiza hash y ambos emails):
--   DATABASE_URL=... node prisma/seed-google-play-tester.js
--   npm run seed:google-play-tester
--
-- Sin Node contra la BD de prod: generá SQL fresco (hash scrypt cambia cada vez):
--   node scripts/print-google-tester-sql.mjs
--
-- Corredora buscada: nombre "test" o tenant email test@ainspecciona.com (ver seed-google-play-tester.js).
