export const AI_PROMPTS_BACKUP_V2_2 = {
  MOBILIARIO_FIJO: [
    "Analiza la imagen correspondiente al slot {{SLOT_CODE}}",
    "bajo el contexto técnico del KPI: MOBILIARIO FIJO.",
    "",
    "Primero describe objetivamente lo que se ve en la imagen.",
    "Luego realiza el análisis SOLO según este KPI.",
    "",
    "Evalúa exclusivamente la presencia visible de las siguientes señales:",
    "",
    "- rayones visibles",
    "- golpes o daños superficiales",
    "- hinchazón o deformación del material",
    "- puertas desalineadas",
    "- herrajes visibles dañados o sueltos",
    "- cubiertas desteñidas o con pérdida visible de color",
    "",
    "Instrucciones estrictas:",
    "- Analiza solo lo que sea visible en la imagen.",
    "- No infieras causas ni funcionamiento.",
    "- No evalúes calidad del material.",
    "- No emitas juicios de severidad.",
    "- No hagas recomendaciones.",
    "",
    "Entrega el resultado en formato estructurado.",
    "",
    "Si no se observa ninguna de las señales listadas,",
    "indícalo explícitamente."
  ].join("\n"),
  MUROS_PINTURA: [
    "Analiza la imagen correspondiente al slot {{SLOT_CODE}}",
    "bajo el contexto técnico del KPI: MUROS Y PINTURA.",
    "",
    "Primero describe objetivamente lo que se ve en la imagen.",
    "Luego realiza el análisis SOLO según este KPI.",
    "",
    "Evalúa exclusivamente la presencia visible de las siguientes señales:",
    "",
    "- rayones visibles",
    "- manchas visibles",
    "- descascaramiento o desprendimiento de pintura",
    "- grietas superficiales",
    "- pintura dispareja o con diferencias evidentes de tono",
    "- marcas visibles por humedad (solo si son evidentes en superficie)",
    "",
    "Instrucciones estrictas:",
    "- Analiza únicamente lo que sea visible en la imagen.",
    "- No infieras causas ni condiciones internas.",
    "- No evalúes estructura ni humedad no visible.",
    "- No emitas juicios de severidad.",
    "- No hagas recomendaciones.",
    "",
    "Entrega el resultado en formato estructurado.",
    "",
    "Si no se observa ninguna de las señales listadas,",
    "indícalo explícitamente."
  ].join("\n"),
  PISOS: [
    "Analiza la imagen correspondiente al slot {{SLOT_CODE}}",
    "bajo el contexto técnico del KPI: PISOS.",
    "",
    "Primero describe objetivamente lo que se ve en la imagen.",
    "Luego realiza el análisis SOLO según este KPI.",
    "",
    "Evalúa exclusivamente la presencia visible de las siguientes señales:",
    "",
    "- rayones visibles",
    "- manchas visibles",
    "- piezas sueltas o levantadas (si es visible)",
    "- quiebres, trizaduras o piezas rotas",
    "- desgaste evidente de la superficie",
    "- diferencias visibles de color o tono entre piezas",
    "",
    "Instrucciones estrictas:",
    "- Analiza únicamente lo que sea visible en la imagen.",
    "- No infieras condiciones internas ni estructurales.",
    "- No evalúes nivelación ni instalación.",
    "- No emitas juicios de severidad.",
    "- No hagas recomendaciones.",
    "",
    "Entrega el resultado en formato estructurado.",
    "",
    "Si no se observa ninguna de las señales listadas,",
    "indícalo explícitamente."
  ].join("\n"),
  HUMEDAD: [
    "Analiza la imagen correspondiente al slot {{SLOT_CODE}}",
    "bajo el contexto técnico del KPI: HUMEDAD VISIBLE.",
    "",
    "Primero describe objetivamente lo que se ve en la imagen.",
    "Luego realiza el análisis SOLO según este KPI.",
    "",
    "Evalúa exclusivamente la presencia visible de las siguientes señales:",
    "",
    "- manchas de humedad visibles",
    "- moho visible",
    "- salitre o eflorescencia visible",
    "- pintura ampollada o levantada asociada a humedad",
    "- oscurecimiento localizado compatible con humedad",
    "",
    "Instrucciones estrictas:",
    "- Analiza únicamente lo que sea claramente visible en la imagen.",
    "- No infieras causas, origen ni profundidad de la humedad.",
    "- No evalúes humedad interna ni condiciones no visibles.",
    "- No emitas juicios de severidad.",
    "- No hagas recomendaciones.",
    "- Describe con detalle lo que se observa cuando haya señales visibles (ubicación y extensión).",
    "",
    "Entrega el resultado en formato estructurado.",
    "",
    "Si no se observa ninguna de las señales listadas,",
    "indícalo explícitamente."
  ].join("\n"),
  SANITARIOS: [
    "Analiza la imagen correspondiente al slot {{SLOT_CODE}}",
    "bajo el contexto técnico del KPI: SANITARIOS.",
    "",
    "Primero describe objetivamente lo que se ve en la imagen.",
    "Luego realiza el análisis SOLO según este KPI.",
    "",
    "Evalúa exclusivamente la presencia visible de las siguientes señales:",
    "",
    "- grietas o trizaduras visibles en artefactos",
    "- quiebres o piezas rotas",
    "- manchas visibles persistentes",
    "- desgaste evidente de superficies",
    "- sellos visibles deteriorados",
    "- corrosión u óxido visible en grifería",
    "- desalineación visible de artefactos (si es evidente)",
    "",
    "Cañerías pintadas (frecuente en entregas inmobiliarias): la pintura sobre tubos visibles NO es por sí sola hallazgo; no confundir con corrosión, humedad o desgaste. Solo señalar si además hay grietas, goteo, óxido en metal expuesto o sellos deteriorados claramente visibles.",
    "",
    "Instrucciones estrictas:",
    "- Analiza únicamente lo que sea visible en la imagen.",
    "- No evalúes funcionamiento ni condiciones internas.",
    "- No infieras fugas, presión de agua ni fallas ocultas.",
    "- No emitas juicios de severidad.",
    "- No hagas recomendaciones.",
    "",
    "Entrega el resultado en formato estructurado.",
    "",
    "Si no se observa ninguna de las señales listadas,",
    "indícalo explícitamente."
  ].join("\n"),
  ELECTRICIDAD: [
    "Analiza la imagen correspondiente al slot {{SLOT_CODE}}",
    "bajo el contexto técnico del KPI: ELECTRICIDAD VISIBLE.",
    "",
    "Primero describe objetivamente lo que se ve en la imagen.",
    "Luego realiza el análisis SOLO según este KPI.",
    "",
    "Evalúa exclusivamente la condición visible de los elementos eléctricos accesibles.",
    "No evalúes funcionamiento interno, normativa ni capacidad eléctrica.",
    "",
    "Detecta únicamente la presencia visible de las siguientes señales:",
    "",
    "- enchufes o interruptores rotos o quebrados",
    "- tapas faltantes o sueltas en enchufes, interruptores o tablero",
    "- cables visibles expuestos",
    "- signos visibles de sobrecalentamiento (quemaduras, derretimiento)",
    "- fijación deficiente visible de enchufes o interruptores",
    "- tablero eléctrico visible sin tapa o con elementos dañados",
    "- presencia visible de interruptor diferencial",
    "- ausencia visible de interruptor diferencial",
    "",
    "Instrucciones estrictas:",
    "- Analiza únicamente lo que sea claramente visible en la imagen.",
    "- No infieras funcionamiento, capacidad, suficiencia ni cumplimiento normativo.",
    "- No evalúes seguridad eléctrica general.",
    "- No emitas juicios de severidad.",
    "- No hagas recomendaciones.",
    "- No utilices lenguaje interpretativo.",
    "",
    "Entrega el resultado en formato estructurado.",
    "",
    "Si no se observa ninguna de las señales listadas,",
    "indícalo explícitamente."
  ].join("\n"),
  VENTANAS_CERRAMIENTOS: [
    "Analiza la imagen correspondiente al slot {{SLOT_CODE}}",
    "bajo el contexto técnico del KPI: VENTANAS Y CERRAMIENTOS.",
    "",
    "Primero describe objetivamente lo que se ve en la imagen.",
    "Luego realiza el análisis SOLO según este KPI.",
    "",
    "Evalúa exclusivamente la condición visible de ventanas y cerramientos.",
    "",
    "Detecta únicamente la presencia visible de las siguientes señales:",
    "",
    "- vidrios trizados o quebrados",
    "- rayones visibles en vidrios",
    "- marcos dañados, deformados o golpeados",
    "- sellos visibles deteriorados o faltantes",
    "- fijación deficiente visible del marco",
    "- corrosión visible en marcos o herrajes expuestos",
    "- suciedad incrustada o manchas persistentes en vidrios (si es evidente)",
    "",
    "Instrucciones estrictas:",
    "- Analiza únicamente lo que sea claramente visible en la imagen.",
    "- No evalúes funcionamiento, apertura/cierre ni hermeticidad.",
    "- No infieras filtraciones ni aislación.",
    "- No emitas juicios de severidad.",
    "- No hagas recomendaciones.",
    "- No utilices lenguaje interpretativo.",
    "",
    "Entrega el resultado en formato estructurado.",
    "",
    "Si no se observa ninguna de las señales listadas,",
    "indícalo explícitamente."
  ].join("\n"),
  PUERTAS_HERRAJES: [
    "Analiza la imagen correspondiente al slot {{SLOT_CODE}}",
    "bajo el contexto técnico del KPI: PUERTAS Y HERRAJES.",
    "",
    "Primero describe objetivamente lo que se ve en la imagen.",
    "Luego realiza el análisis SOLO según este KPI.",
    "",
    "Evalúa exclusivamente la condición visible de puertas y sus herrajes asociados.",
    "",
    "Detecta únicamente la presencia visible de las siguientes señales:",
    "",
    "- puertas rayadas o con daños visibles",
    "- golpes o abolladuras visibles",
    "- desprendimiento o desgaste evidente de pintura o terminación",
    "- puertas visiblemente deformadas",
    "- marcos dañados o golpeados",
    "- bisagras visibles dañadas o faltantes",
    "- manillas o cerraduras visibles dañadas",
    "- fijación deficiente visible de herrajes",
    "- holguras visibles evidentes entre puerta y marco",
    "",
    "Instrucciones estrictas:",
    "- Analiza únicamente lo que sea claramente visible en la imagen.",
    "- No evalúes funcionamiento, ajuste ni seguridad.",
    "- No infieras fallas ocultas.",
    "- No emitas juicios de severidad.",
    "- No hagas recomendaciones.",
    "- No utilices lenguaje interpretativo.",
    "",
    "Entrega el resultado en formato estructurado.",
    "",
    "Si no se observa ninguna de las señales listadas,",
    "indícalo explícitamente."
  ].join("\n")
};
